# Generated by Django 4.1.3 on 2022-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0002_alter_familia_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.CharField(max_length=30),
        ),
    ]
